### ISSUE TITLE
Please add a way to check the goal in-game

### ISSUE THREAD

**Issue by thislooksfun** [Seldom-SE/archipelago_terraria_client#3]
Some of us like to randomize our goal, for added randomness. That generates just fine, but there is currently no way to check the goal in-game. It's possible to derive it from other sources (seeing what checks are included, using PopTracker, or just reading the spoiler log, if one was generated), but it would be nicer if there was a way to do it natively in-game. For example, Hollow Knight has a location in-game you can interact with to see what your goal is. Maybe you could make talking to the guide (or some other such npc) show it?

**Comment by Seldom-SE** [comment]
It's not very flashy, but `/apdebug` shows the goal

**Comment by thislooksfun** [comment]
Ah, I didn't realize that was a command usable in-game. My bad!
