### ISSUE TITLE
Zenith goal broken in 1.4.4

### ISSUE THREAD

**Issue by enchanted-sword** [Seldom-SE/archipelago_terraria_client#4]
With the Zenith achievement added in 1.4.4, crafting the Zenith doesn't seem to trigger victory on either the current official APWorld or the beta Calamity APWorld. I haven't tested this yet without other mods, but I tried crafting it entirely in the vanilla inventory to be safe instead of using any sort of modded inventory container and it still only awarded the achievement without counting as victory.

**Comment by enchanted-sword** [comment]
Might have been able to resolve the issue locally when using the official APWorld, but it still remains the case for the newer APWorld.

**Comment by Seldom-SE** [comment]
Thanks for the report, fixed in https://github.com/Seldom-SE/archipelago_terraria_client/commit/df76dc3612974fab84dbd7aee6497ec7c741559c. I had changed the location name to "Infinity +1 Sword" in the apworld, but not in the client, lol
